import { Injectable } from '@nestjs/common';

@Injectable()
export class AppService {
  getDashboardHtml(): string {
    return [
      '<!doctype html>',
      '<html lang="en">',
      '<head>',
      '  <meta charset="utf-8" />',
      '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
      '  <title>Site Activity Monitor</title>',
      '  <style>',
      '    :root { color-scheme: dark; --bg: #06111f; --panel: rgba(8, 16, 30, 0.82); --border: rgba(148, 163, 184, 0.16); --text: #e8eef7; --muted: #96a8c0; --accent: #35d39a; --danger: #fb7185; }',
      '    * { box-sizing: border-box; }',
      '    body { margin: 0; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: var(--text); background: radial-gradient(circle at top left, rgba(53, 211, 154, 0.18), transparent 25%), radial-gradient(circle at top right, rgba(96, 165, 250, 0.18), transparent 22%), linear-gradient(180deg, #07111f 0%, #040913 100%); }',
      '    .shell { max-width: 1200px; margin: 0 auto; padding: 28px 18px 42px; }',
      '    .hero, .panel, .stat { background: var(--panel); border: 1px solid var(--border); border-radius: 22px; box-shadow: 0 20px 70px rgba(0, 0, 0, 0.35); backdrop-filter: blur(16px); }',
      '    .hero { display: grid; grid-template-columns: 1.3fr 0.7fr; gap: 18px; padding: 24px; margin-bottom: 18px; }',
      '    .eyebrow { display: inline-flex; padding: 7px 11px; border-radius: 999px; background: rgba(255,255,255,0.05); color: var(--muted); font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; }',
      '    h1 { margin: 16px 0 10px; font-size: clamp(34px, 5vw, 62px); line-height: 0.95; letter-spacing: -0.06em; }',
      '    .lead { margin: 0; max-width: 60ch; color: var(--muted); line-height: 1.65; }',
      '    .hero-actions, .row, .actions { display: flex; gap: 10px; flex-wrap: wrap; }',
      '    .btn { appearance: none; border: 0; cursor: pointer; border-radius: 14px; padding: 12px 16px; font-weight: 700; color: #06111f; background: linear-gradient(135deg, #8bffca, #57c8ff); }',
      '    .btn.secondary { color: var(--text); background: rgba(255,255,255,0.06); border: 1px solid var(--border); }',
      '    .stats { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }',
      '    .stat { padding: 18px; }',
      '    .stat span, label { display: block; color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; margin-bottom: 8px; }',
      '    .stat strong { font-size: 28px; letter-spacing: -0.04em; }',
      '    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }',
      '    .panel { padding: 20px; }',
      '    .form { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; }',
      '    .full { grid-column: 1 / -1; }',
      '    input, select { width: 100%; border-radius: 14px; border: 1px solid var(--border); background: rgba(3, 8, 17, 0.8); color: var(--text); padding: 12px 14px; font: inherit; }',
      '    .list { display: grid; gap: 12px; }',
      '    .item { border: 1px solid var(--border); border-radius: 18px; padding: 16px; background: rgba(4, 9, 18, 0.76); }',
      '    .item-head { display: flex; justify-content: space-between; gap: 12px; align-items: start; }',
      '    .meta { margin: 4px 0 0; color: var(--muted); font-size: 13px; line-height: 1.5; word-break: break-word; }',
      '    .badge { display: inline-flex; align-items: center; padding: 7px 10px; border-radius: 999px; border: 1px solid var(--border); font-size: 12px; font-weight: 700; }',
      '    .up { color: var(--accent); } .down { color: var(--danger); } .unknown { color: #fbbf24; }',
      '    pre { margin: 0; white-space: pre-wrap; word-break: break-word; color: #d9e7ff; background: rgba(3, 8, 17, 0.8); border: 1px solid var(--border); border-radius: 18px; padding: 16px; min-height: 200px; }',
      '    .toast { position: fixed; right: 18px; bottom: 18px; padding: 14px 16px; border-radius: 16px; background: rgba(7, 17, 31, 0.95); border: 1px solid var(--border); box-shadow: 0 20px 70px rgba(0,0,0,.4); opacity: 0; transform: translateY(12px); transition: 0.2s ease; }',
      '    .toast.show { opacity: 1; transform: translateY(0); }',
      '    @media (max-width: 900px) { .hero, .grid { grid-template-columns: 1fr; } }',
      '    @media (max-width: 640px) { .shell { padding: 16px 12px 24px; } .form, .stats { grid-template-columns: 1fr; } }',
      '  </style>',
      '</head>',
      '<body>',
      '  <div class="shell">',
      '    <section class="hero">',
      '      <div>',
      '        <div class="eyebrow">Site Activity Monitor</div>',
      '        <h1>Track uptime.<br />React faster.</h1>',
      '        <p class="lead">A local dashboard for your NestJS monitor backend. Add sites, pause them, inspect recent checks, and see the current state at a glance.</p>',
      '        <div class="hero-actions" style="margin-top:20px;">',
      '          <button class="btn" id="refreshBtn" type="button">Refresh</button>',
      '          <button class="btn secondary" id="demoBtn" type="button">Load first monitor</button>',
      '        </div>',
      '      </div>',
      '      <div class="stats">',
      '        <div class="stat"><span>Total</span><strong id="totalCount">0</strong></div>',
      '        <div class="stat"><span>Active</span><strong id="activeCount">0</strong></div>',
      '        <div class="stat"><span>Down</span><strong id="downCount">0</strong></div>',
      '        <div class="stat"><span>Uptime avg</span><strong id="uptimeAvg">0%</strong></div>',
      '      </div>',
      '    </section>',
      '    <section class="grid">',
      '      <article class="panel">',
      '        <h2>Create monitor</h2>',
      '        <form id="monitorForm" class="form">',
      '          <label class="full">Name <input name="name" placeholder="Example Site" required /></label>',
      '          <label class="full">URL <input name="url" placeholder="https://example.com" required /></label>',
      '          <label>Interval (minutes) <input name="interval" type="number" min="1" value="5" required /></label>',
      '          <label>Active <select name="isActive"><option value="true">Yes</option><option value="false">No</option></select></label>',
      '          <div class="actions full"><button class="btn" type="submit">Save monitor</button><button class="btn secondary" type="reset">Reset</button></div>',
      '        </form>',
      '      </article>',
      '      <article class="panel">',
      '        <h2>Monitors</h2>',
      '        <div id="monitorList" class="list"></div>',
      '      </article>',
      '    </section>',
      '    <section class="panel" style="margin-top:18px;">',
      '      <h2 id="detailsTitle">Stats and history</h2>',
      '      <pre id="detailsBox">Choose a monitor to see stats and history.</pre>',
      '    </section>',
      '  </div>',
      '  <div id="toast" class="toast"></div>',
      '  <script>',
      '    const state = { monitors: [], selectedId: null };',
      '    const totalCount = document.getElementById("totalCount");',
      '    const activeCount = document.getElementById("activeCount");',
      '    const downCount = document.getElementById("downCount");',
      '    const uptimeAvg = document.getElementById("uptimeAvg");',
      '    const monitorList = document.getElementById("monitorList");',
      '    const detailsTitle = document.getElementById("detailsTitle");',
      '    const detailsBox = document.getElementById("detailsBox");',
      '    const toastEl = document.getElementById("toast");',
      '    const refreshBtn = document.getElementById("refreshBtn");',
      '    const demoBtn = document.getElementById("demoBtn");',
      '    const monitorForm = document.getElementById("monitorForm");',
      '    function toast(message) { toastEl.textContent = message; toastEl.classList.add("show"); clearTimeout(window.__toastTimer); window.__toastTimer = setTimeout(function () { toastEl.classList.remove("show"); }, 2400); }',
      '    function esc(value) { return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("\"", "&quot;").replaceAll("\'", "&#39;"); }',
      '    async function requestJson(url, options) { const response = await fetch(url, Object.assign({ headers: { "Content-Type": "application/json" } }, options || {})); if (!response.ok) { throw new Error(await response.text() || "Request failed"); } const contentType = response.headers.get("content-type") || ""; return contentType.indexOf("application/json") >= 0 ? response.json() : response.text(); }',
      '    function badge(status) { var normalized = status || "unknown"; return \'<span class="badge \' + normalized + \'">\' + esc(String(normalized).toUpperCase()) + \'</span>\'; }',
      '    function uptime(monitors) { if (!monitors.length) { return 0; } var total = monitors.reduce(function (sum, monitor) { return sum + Number(monitor.uptimePercent || 0); }, 0); return Math.round(total / monitors.length); }',
      '    function render(monitors) { totalCount.textContent = String(monitors.length); activeCount.textContent = String(monitors.filter(function (m) { return m.isActive; }).length); downCount.textContent = String(monitors.filter(function (m) { return (m.lastStatus || "unknown") === "down"; }).length); uptimeAvg.textContent = String(uptime(monitors)) + "%"; if (!monitors.length) { monitorList.innerHTML = \'<div class="item">No monitors yet. Use the form to create one.</div>\'; return; } monitorList.innerHTML = monitors.map(function (monitor) { var id = monitor._id || monitor.id; var lastChecked = monitor.lastCheckedAt ? new Date(monitor.lastCheckedAt).toLocaleString() : "Never"; return \'<div class="item"><div class="item-head"><div><strong>\' + esc(monitor.name) + \'</strong><p class="meta">\' + esc(monitor.url) + \'</p><p class="meta">Interval: \' + esc(monitor.interval) + \' min · Last checked: \' + esc(lastChecked) + \'</p></div>\' + badge(monitor.lastStatus) + \'</div><div class="row" style="margin-top:12px;"><button class="btn secondary" type="button" data-action="details" data-id="\' + esc(id) + \'">History & stats</button><button class="btn secondary" type="button" data-action="pause" data-id="\' + esc(id) + \'">Pause</button><button class="btn secondary" type="button" data-action="delete" data-id="\' + esc(id) + \'">Delete</button></div></div>\'; }).join(""); }',
      '    async function loadMonitors() { var monitors = await requestJson("/monitors"); state.monitors = Array.isArray(monitors) ? monitors : []; render(state.monitors); if (!state.selectedId && state.monitors[0]) { state.selectedId = state.monitors[0]._id || state.monitors[0].id; } }',
      '    async function loadDetails(id) { var result = await Promise.all([requestJson("/monitors/" + id + "/stats"), requestJson("/monitors/" + id + "/history")]); var stats = result[0]; var history = result[1]; var monitor = state.monitors.find(function (item) { return (item._id || item.id) === id; }); detailsTitle.textContent = monitor ? monitor.name + " · stats and history" : "Stats and history"; detailsBox.textContent = JSON.stringify({ stats: stats, history: Array.isArray(history) ? history.slice(0, 10) : history }, null, 2); }',
      '    monitorList.addEventListener("click", async function (event) { var button = event.target.closest("button[data-action]"); if (!button) { return; } var action = button.dataset.action; var id = button.dataset.id; if (action === "details") { state.selectedId = id; await loadDetails(id); return; } if (action === "pause") { await requestJson("/monitors/" + id + "/pause", { method: "PATCH" }); toast("Monitor paused"); await loadMonitors(); return; } if (action === "delete") { await requestJson("/monitors/" + id, { method: "DELETE" }); toast("Monitor removed"); await loadMonitors(); if (state.selectedId === id) { state.selectedId = null; detailsBox.textContent = "Choose a monitor to see stats and history."; } } });',
      '    monitorForm.addEventListener("submit", async function (event) { event.preventDefault(); var formData = new FormData(event.currentTarget); await requestJson("/monitors", { method: "POST", body: JSON.stringify({ name: formData.get("name"), url: formData.get("url"), interval: Number(formData.get("interval")), isActive: formData.get("isActive") === "true" }) }); event.currentTarget.reset(); toast("Monitor created"); await loadMonitors(); });',
      '    refreshBtn.addEventListener("click", async function () { await loadMonitors(); if (state.selectedId) { await loadDetails(state.selectedId); } toast("Dashboard refreshed"); });',
      '    demoBtn.addEventListener("click", async function () { if (!state.monitors[0]) { toast("No monitors yet"); return; } state.selectedId = state.monitors[0]._id || state.monitors[0].id; await loadDetails(state.selectedId); toast("Loaded first monitor"); });',
      '    loadMonitors().catch(function (error) { monitorList.innerHTML = \'<div class="item">Failed to load monitors. Make sure the Nest app is running.</div>\'; detailsBox.textContent = String(error && error.message ? error.message : error); toast("Failed to load dashboard"); });',
      '  </script>',
      '</body>',
      '</html>',
    ].join("\n");
  }
}